src/Pars/Areas/Identity/Controllers/LoginController.cs
using Pars.Services.Contracts.Identity;
using Pars.ViewModels.Identity.Settings;
using Pars.ViewModels.Identity;
using DNTBreadCrumb.Core;
using DNTCaptcha.Core;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using System.Threading.Tasks;
using DNTCommon.Web.Core;
using System;

namespace Pars.Areas.Identity.Controllers
{
    [Area(AreaConstants.IdentityArea)]
    [AllowAnonymous]
    //[BreadCrumb(Title = "ورود به سیستم", UseDefaultRouteUrl = true, Order = 0)]
    public class LoginController : Controller
    {
        private readonly ILogger<LoginController> _logger;
        private readonly IApplicationSignInManager _signInManager;
        private readonly IApplicationUserManager _userManager;
        private readonly IOptionsSnapshot<SiteSettings> _siteOptions;

        public LoginController(
            IApplicationSignInManager signInManager,
            IApplicationUserManager userManager,
            IOptionsSnapshot<SiteSettings> siteOptions,
            ILogger<LoginController> logger)
        {
            _signInManager = signInManager ?? throw new ArgumentNullException(nameof(signInManager));
            _userManager = userManager ?? throw new ArgumentNullException(nameof(userManager));
            _siteOptions = siteOptions ?? throw new ArgumentNullException(nameof(siteOptions));
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }

        //[BreadCrumb(Title = "ایندکس", Order = 1)]
        [NoBrowserCache]
        public IActionResult Index(string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        //[ValidateDNTCaptcha(CaptchaGeneratorLanguage = Language.Persian,
        //                    CaptchaGeneratorDisplayMode = DisplayMode.SumOfTwoNumbers)]
        public async Task<IActionResult> Index(LoginViewModel model, string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByNameAsync(model.Username);
                if (user == null)
                {
                    ModelState.AddModelError(string.Empty, "نام کاربری و یا کلمه‌ی عبور وارد شده معتبر نیستند.");
                    return View(model);
                }

                if (!user.IsActive)
                {
                    ModelState.AddModelError(string.Empty, "اکانت شما غیرفعال شده‌است.");
                    return View(model);
                }

                if (_siteOptions.Value.EnableEmailConfirmation &&
                    !await _userManager.IsEmailConfirmedAsync(user))
                {
                    ModelState.AddModelError("", "لطفا به پست الکترونیک خود مراجعه کرده و ایمیل خود را تائید کنید!");
                    return View(model);
                }

                var result = await _signInManager.PasswordSignInAsync(
                                        model.Username,
                                        model.Password,
                                        model.RememberMe,
                                        lockoutOnFailure: true);
                if (result.Succeeded || result.RequiresTwoFactor || result.IsLockedOut)
                {
                    _logger.LogInformation(1, $"{model.Username} logged in.");
                    if (Url.IsLocalUrl(returnUrl))
                    {
                        return Redirect(returnUrl);
                    }
                    return RedirectToAction(nameof(HomeController.Index), "Home");
                }

                //if (result.RequiresTwoFactor)
                //{
                //    return RedirectToAction(
                //        nameof(TwoFactorController.SendCode),
                //        "TwoFactor",
                //        new { ReturnUrl = returnUrl, RememberMe = model.RememberMe });
                //}
                //if (result.IsLockedOut)
                //{
                //    _logger.LogWarning(2, $"{model.Username} قفل شده‌است.");
                //    return View("~/Areas/Identity/Views/TwoFactor/Lockout.cshtml");
                //}

                if (result.IsNotAllowed)
                {
                    ModelState.AddModelError(string.Empty, "عدم دسترسی ورود.");
                    return View(model);
                }

                ModelState.AddModelError(string.Empty, "نام کاربری و یا کلمه‌ی عبور وارد شده معتبر نیستند.");
                return View(model);
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }

        public async Task<IActionResult> LogOff()
        {
            var user = User.Identity.IsAuthenticated ? await _userManager.FindByNameAsync(User.Identity.Name) : null;
            await _signInManager.SignOutAsync();
            if (user != null)
            {
                await _userManager.UpdateSecurityStampAsync(user);
                _logger.LogInformation(4, $"{user.UserName} logged out.");
            }

            return RedirectToAction(nameof(HomeController.Index), "Home");
        }
    }
}

src/Pars/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Pars.Services.Contracts;

namespace Pars.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoryService _categoryService;

        public CategoryController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _categoryService.GetAllAsync());
        }
    }
}

src/Pars/Controllers/OrderBasketController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DNTCommon.Web.Core;
using Microsoft.AspNetCore.Authorization;
using Pars.Common.Enums;
using Pars.Services.Contracts;
using Pars.ViewModels.OrderBaskets;
using Pars.ViewModels.Orders;

namespace Pars.Controllers
{
    [Authorize]
    public class OrderBasketController : Controller
    {
        private readonly IOrderBasketService _orderBasketService;

        public OrderBasketController(IOrderBasketService orderBasketService)
        {
            _orderBasketService = orderBasketService;
        }

        [AjaxOnly, HttpGet]
        public async Task<IActionResult> Add(OrderBasketInput input)
        {
            var userId = User.Identity.GetUserId<int>();
            await _orderBasketService.AddAsync(userId, input.ProductId, input.Count);
            return await Card();
        }

        [AjaxOnly, HttpGet]
        public async Task<IActionResult> Subtract(OrderBasketInput input)
        {
            var userId = User.Identity.GetUserId<int>();
            await _orderBasketService.SubtractAsync(userId, input.ProductId, input.Count);
            return await Card();
        }

        [AjaxOnly, HttpGet]
        public async Task<IActionResult> Remove(Guid id)
        {
            var userId = User.Identity.GetUserId<int>();
            await _orderBasketService.RemoveAsync(userId, id);
            return await Card();
        }

        [AjaxOnly, HttpGet]
        public async Task<IActionResult> Clear()
        {
            var userId = User.Identity.GetUserId<int>();
            await _orderBasketService.ClearAsync(userId);
            return await Card();
        }
        [AjaxOnly, HttpGet]
        public async Task<IActionResult> Card()
        {
            var userId = User.Identity.GetUserId<int>();
            var model = await _orderBasketService.GetAllAsync(userId);
            return PartialView("_OrderBasket", model);
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var userId = User.Identity.GetUserId<int>();
            var model = await _orderBasketService.GetAllForSubmitAsync(userId);
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Submit()
        {
            var userId = User.Identity.GetUserId<int>();
            await _orderBasketService.SubmitAsync(userId);
            await _orderBasketService.ClearAsync(userId);
            return RedirectToAction("Index", "Order", new { OrderStatus = OrderStatus.New });
        }
    }
}

src/Pars/Controllers/ProductController.cs
using System.Linq;
using DNTCommon.Web.Core;
using Microsoft.AspNetCore.Mvc;
using Pars.Services.Contracts;
using Pars.ViewModels;
using Pars.ViewModels.Products;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Pars.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _productService;
        private readonly ICategoryService _categoryService;
        private readonly IWarehouseService _warehouseService;

        public ProductController(IProductService productService, ICategoryService categoryService, IWarehouseService warehouseService)
        {
            _productService = productService;
            _categoryService = categoryService;
            _warehouseService = warehouseService;
        }

        [HttpGet]
        public async Task<IActionResult> Index([FromQuery] string categoryId, [FromQuery] string warehouseId, [FromQuery] string title)
        {
            ViewBag.Title = !string.IsNullOrWhiteSpace(title) ? title : "لیست محصولات";

            var model = new SearchProductsViewModel() { CategoryId = categoryId, WarehouseId = warehouseId };
            var result = new ProductIndexViewModel
            {
                PagedListViewModel = await _productService.GetAllAsync(model),
                SearchViewModel = model,
                Warehouses = (await _warehouseService.GetAllForDropDownAsync())
                    .Select(x =>
                        new SelectListItem(x.Name, x.Id,
                            !string.IsNullOrWhiteSpace(warehouseId) && x.Id == warehouseId)).ToList(),
                Categories = (await _categoryService.GetAllForDropDownAsync())
                    .Select(x =>
                        new SelectListItem(x.Name, x.Id, !string.IsNullOrWhiteSpace(categoryId) && x.Id == categoryId))
                    .ToList(),
            };

            return View(result);
        }

        [AjaxOnly, HttpGet]
        [ResponseCache(Location = ResponseCacheLocation.None, NoStore = true)]
        public async Task<IActionResult> Search(SearchProductsViewModel model)
        {
            var result = new PagedListResult<ProductListItemViewModel, SearchProductsViewModel>
            {
                PagedListViewModel = await _productService.GetAllAsync(model),
                SearchViewModel = model,
            };

            return PartialView("_Table", result);
        }

        [HttpGet]
        public async Task<IActionResult> Detail(string id)
        {
            return View(await _productService.GetAsync(id));
        }
    }
}

src/Pars/Controllers/WarehouseController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Pars.Services.Contracts;

namespace Pars.Controllers
{
    public class WarehouseController : Controller
    {
        private readonly IWarehouseService _warehouseService;

        public WarehouseController(IWarehouseService warehouseService)
        {
            _warehouseService = warehouseService;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _warehouseService.GetAllAsync());
        }
    }
}

src/Pars/Views/Shared/AccessDenied.cshtml
@{
    ViewData["Title"] = "عدم دسترسی!";
    this.Context.Response.StatusCode = (int)HttpStatusCode.Unauthorized;
}

<div class="card panel-danger mt-5">
    <div class="card-header">
        <h5 class="card-title">@ViewData["Title"]</h5>
    </div>
    <div class="card-body">
        متاسفانه شما مجوز دسترسی به صفحه‌ی درخواستی را ندارید.
    </div>
</div>

src/Pars/Views/Shared/NotFound.cshtml
@{
    ViewData["Title"] = "یافت نشد!";
    this.Context.Response.StatusCode = (int)HttpStatusCode.Gone;
}

<div class="mt-5">
    <div class="alert alert-warning">
        <h1><span aria-hidden="true" class="fas fa-warning"></span>خطا</h1>
        <h3>اطلاعات درخواستی یافت نشد.</h3>
    </div>
</div>

src/Pars/Views/Shared/_CustomValidationSummary.cshtml
@if (ViewData.ModelState.Any(keyValuePair => keyValuePair.Value.Errors.Any()))
{
    <div class="alert alert-warning">
        <a href="#" class="close" data-dismiss="alert">×</a>
        <h4>خطاهای اعتبارسنجی</h4>
        <div asp-validation-summary="ModelOnly"></div>
    </div>
}

src/Pars/Views/Shared/_HeaderMenu.cshtml
@using Pars.Common.Enums
<li class="menu-item" data-menu-toggle="click" aria-haspopup="true">
    <a asp-controller="Home" asp-action="Index" asp-area="@AreaConstants.IdentityArea" class="menu-link">
        <span class="menu-text">پیشخوان</span>
    </a>
</li>
<li class="menu-item  menu-item-submenu menu-item-rel" data-menu-toggle="click" aria-haspopup="true">
    <a href="javascript:;" class="menu-link menu-toggle">
        <span class="menu-text">سفارشات</span><i class="menu-arrow"></i>
    </a>
    <div class="menu-submenu menu-submenu-classic menu-submenu-left">
        <ul class="menu-subnav">
            <li class="menu-item " aria-haspopup="true">
                <a asp-controller="OrderBasket" asp-action="Index" asp-area="" class="menu-link ">
                    <span class="menu-text">ثبت سفارش</span><span class="menu-desc"></span>
                </a>
            </li>
            <li class="menu-item " aria-haspopup="true">
                <a asp-controller="Order" asp-action="Index" asp-area="" asp-route-title="لیست سفارشات جدید" asp-route-orderStatus="@OrderStatus.New.ToString()" class="menu-link ">
                    <span class="menu-text">لیست سفارشات جدید</span><span class="menu-desc"></span>
                </a>
            </li>
            <li class="menu-item " aria-haspopup="true">
                <a asp-controller="Order" asp-action="Index" asp-area="" asp-route-title="لیست سفارشات در حال تولید" asp-route-orderStatus="@OrderStatus.InProgress.ToString()" class="menu-link ">
                    <span class="menu-text">سفارشات در حال تولید</span><span class="menu-desc"></span>
                </a>
            </li>
            <li class="menu-item " aria-haspopup="true">
                <a asp-controller="Order" asp-action="Index" asp-area="" asp-route-title="لیست سفارشات تحویل شده" asp-route-orderStatus="@OrderStatus.Delivered.ToString()" class="menu-link ">
                    <span class="menu-text">سفارشات تحویل شده</span><span class="menu-desc"></span>
                </a>
            </li>
        </ul>
    </div>
</li>
<li class="menu-item  menu-item-submenu menu-item-rel" data-menu-toggle="click" aria-haspopup="true">
    <a href="javascript:;" class="menu-link menu-toggle">
        <span class="menu-text">محصولات</span><i class="menu-arrow"></i>
    </a>
    <div class="menu-submenu menu-submenu-classic menu-submenu-left">
        <ul class="menu-subnav">
            <li class="menu-item " aria-haspopup="true">
                <a asp-controller="Category" asp-action="Index" asp-area="" class="menu-link ">
                    <span class="menu-text">دسته بندی محصولات</span><span class="menu-desc"></span>
                </a>
            </li>
            <li class="menu-item " aria-haspopup="true">
                <a asp-controller="Product" asp-action="Index" asp-area="" asp-route-title="لیست محصولات" class="menu-link ">
                    <span class="menu-text"> لیست محصولات</span><span class="menu-desc"></span>
                </a>
            </li>
        </ul>
    </div>
</li>
<li class="menu-item  menu-item-submenu menu-item-rel" data-menu-toggle="click" aria-haspopup="true">
    <a href="javascript:;" class="menu-link menu-toggle">
        <span class="menu-text">انبار</span><i class="menu-arrow"></i>
    </a>
    <div class="menu-submenu menu-submenu-classic menu-submenu-left">
        <ul class="menu-subnav">
            <li class="menu-item " aria-haspopup="true">
                <a asp-controller="Warehouse" asp-action="Index" asp-area="" class="menu-link ">
                    <span class="menu-text">لیست انبار ها</span><span class="menu-desc"></span>
                </a>
            </li>
            <li class="menu-item " aria-haspopup="true">
                <a asp-controller="Product" asp-action="Index" asp-area="" asp-route-title="محتویات انبار ها" class="menu-link ">
                    <span class="menu-text">محتویات انبار ها</span><span class="menu-desc"></span>
                </a>
            </li>
        </ul>
    </div>
</li>

src/Pars/Views/Shared/_HeaderUserMenu.cshtml
@inject IUsersPhotoService PhotoService

@{
    var displayName = User.Identity.GetUserDisplayName();
    var photoUrl = PhotoService.GetCurrentUserPhotoUrl();
}
<div class="topbar-item" data-toggle="dropdown" data-offset="0px,0px">
    <div class="btn btn-icon btn-hover-transparent-white d-flex align-items-center btn-lg px-md-2 w-md-auto">
        <span class="text-white opacity-70 font-weight-bold font-size-base d-none d-md-inline mr-1">سلام,</span>
        <span class="text-white opacity-90 font-weight-bolder font-size-base d-none d-md-inline mr-4">@displayName</span>
        <span class="symbol symbol-35">
            <img class="img-thumbnail userImage" src="@photoUrl" alt="@displayName" asp-append-version="true"
                 onerror="this.style.visibility = 'hidden';this.width=0; this.height=0;" />
            @*<span class="symbol-label text-white font-size-h5 font-weight-bold bg-white-o-30">S</span>*@
        </span>
    </div>
</div>

<div class="dropdown-menu p-0 m-0 dropdown-menu-right dropdown-menu-anim-up dropdown-menu-lg p-0">
    <div class="d-flex align-items-center p-8 rounded-top">
        <div class="symbol symbol-md bg-light-primary mr-3 flex-shrink-0">
            <img class="img-thumbnail userImage" src="@photoUrl" alt="@displayName" asp-append-version="true"
                 onerror="this.style.visibility = 'hidden';this.width=0; this.height=0;" />
        </div>
        <div class="text-dark m-0 flex-grow-1 mr-3 font-size-h5">@displayName</div>
    </div>
    <div class="separator separator-solid"></div>
    <div class="navi navi-spacer-x-0 pt-5">
        <!--begin::Item-->
        <a asp-controller="UserCard" asp-action="Index" asp-area="@AreaConstants.IdentityArea" class="navi-item px-8">
            <div class="navi-link">
                <div class="navi-icon mr-2">
                    <i class="flaticon2-calendar-3 text-success"></i>
                </div>
                <div class="navi-text">
                    <div class="font-weight-bold">
                        برگه‌ی کاربری من
                    </div>
                    <div class="text-muted">
                        مشاهده اطلاعات کاربری
                    </div>
                </div>
            </div>
        </a>
        <!--end::Item-->
        <!--begin::Item-->
        <a asp-controller="UserProfile" asp-action="Index" asp-area="@AreaConstants.IdentityArea" class="navi-item px-8">
            <div class="navi-link">
                <div class="navi-icon mr-2">
                    <i class="flaticon2-calendar-3 text-warning"></i>
                </div>
                <div class="navi-text">
                    <div class="font-weight-bold">
                        تنظیمات کاربری من
                    </div>
                    <div class="text-muted">
                        تنظیمات اکانت
                    </div>
                </div>
            </div>
        </a>
        <!--end::Item-->
        <!--begin::Item-->
        <a asp-controller="ChangePassword" asp-action="Index" asp-area="@AreaConstants.IdentityArea" class="navi-item px-8">
            <div class="navi-link">
                <div class="navi-icon mr-2">
                    <i class="fas fa-asterisk text-danger"></i>
                </div>
                <div class="navi-text">
                    <div class="font-weight-bold">
                        تغییر کلمه‌ی عبور
                    </div>
                </div>
            </div>
        </a>
        <!--end::Item-->
        <!--begin::Footer-->
        <div class="navi-separator mt-3"></div>
        <div class="navi-footer  px-8 py-5">
            <a  asp-controller="Login" asp-action="LogOff" asp-area="@AreaConstants.IdentityArea" target="_blank" class="btn btn-light-primary font-weight-bold">خروج</a>
        </div>
        <!--end::Footer-->
    </div>
    <!--end::Nav-->
</div>
<!--end::دراپ دان-->

src/Pars/Views/Shared/_OrderBasket.cshtml
@model List<Pars.Entities.OrderBasket>
<div class="dropdown">
    <div class="topbar-item"
         data-toggle="dropdown"
         data-offset="10px,0px">
        <div class="
                        btn
                        btn-icon
                        btn-hover-transparent-white
                        btn-dropdown
                        btn-lg
                        mr-1
                      ">
            <span class="svg-icon svg-icon-xl">
                @if (@Model.Count > 0)
                {
                    @Model.Count
                }
                <svg xmlns="http://www.w3.org/2000/svg"
                     xmlns:xlink="http://www.w3.org/1999/xlink"
                     width="24px"
                     height="24px"
                     viewBox="0 0 24 24"
                     version="1.1">
                    <g stroke="none"
                       stroke-width="1"
                       fill="none"
                       fill-rule="evenodd">
                        <rect x="0" y="0" width="24" height="24" />
                        <path d="M12,4.56204994 L7.76822128,9.6401844 C7.4146572,10.0644613 6.7840925,10.1217854 6.3598156,9.76822128 C5.9355387,9.4146572 5.87821464,8.7840925 6.23177872,8.3598156 L11.2317787,2.3598156 C11.6315738,1.88006147 12.3684262,1.88006147 12.7682213,2.3598156 L17.7682213,8.3598156 C18.1217854,8.7840925 18.0644613,9.4146572 17.6401844,9.76822128 C17.2159075,10.1217854 16.5853428,10.0644613 16.2317787,9.6401844 L12,4.56204994 Z"
                              fill="#000000"
                              fill-rule="nonzero"
                              opacity="0.3" />
                        <path d="M3.5,9 L20.5,9 C21.0522847,9 21.5,9.44771525 21.5,10 C21.5,10.132026 21.4738562,10.2627452 21.4230769,10.3846154 L17.7692308,19.1538462 C17.3034221,20.271787 16.2111026,21 15,21 L9,21 C7.78889745,21 6.6965779,20.271787 6.23076923,19.1538462 L2.57692308,10.3846154 C2.36450587,9.87481408 2.60558331,9.28934029 3.11538462,9.07692308 C3.23725479,9.02614384 3.36797398,9 3.5,9 Z M12,17 C13.1045695,17 14,16.1045695 14,15 C14,13.8954305 13.1045695,13 12,13 C10.8954305,13 10,13.8954305 10,15 C10,16.1045695 10.8954305,17 12,17 Z"
                              fill="#000000" />
                    </g>
                </svg>
            </span>
        </div>
    </div>
    <div class="dropdown-menu p-0 m-0 dropdown-menu-right dropdown-menu-xl dropdown-menu-anim-up">
        <form>
            <div class="d-flex align-items-center py-10 px-8 bgi-size-cover bgi-no-repeat rounded-top" style="background-image: url(metronic/assets/media/misc/bg-1.jpg);">
                <span class="btn btn-md btn-icon bg-white-o-15 mr-4">
                    <i class="flaticon2-shopping-cart-1 text-success"></i>
                </span>
                <h4 class="text-white m-0 flex-grow-1 mr-3">
                    سبد سفارش من
                </h4>
                <button type="button" class="btn btn-success btn-sm">
                    @(Model.Count) مورد
                </button>
            </div>
            <div class="scroll scroll-push" data-scroll="true" data-height="250" data-mobile-height="200">
                @if (!Model.Any())
                {
                    <div class="d-flex align-items-center justify-content-between p-8">
                        <h4>سبد سفارش خالی است</h4>
                    </div>
                }
                else
                {
                    foreach (var item in Model)
                    {
                        <div class="d-flex align-items-center justify-content-between p-8">
                            <div class="d-flex flex-column mr-2">
                                <a href="@Url.Action("Detail","Product",new{id=item.ProductId})" target="_blank" class="font-weight-bold text-dark-75 font-size-lg text-hover-primary">@item.Name</a>
                                <span class="text-muted">@item.CreationDate.ToFriendlyPersianDateTextify()</span>
                                <div class="d-flex align-items-center mt-2">
                                    <span class="font-weight-bold mr-1 text-dark-75 font-size-lg">@item.Price.ToString("N0") ریال</span>
                                    <span class="text-muted mr-1"> </span>
                                    <button type="button" class="btn btn-xs btn-light-success btn-icon mr-2" onclick="decreaseBasketItem(@item.ProductId)"><i class="ki ki-minus icon-xs"></i></button>
                                    <span class="font-weight-bold mr-2 text-dark-75 font-size-lg">@item.Count</span>
                                    <button type="button" class="btn btn-xs btn-light-success btn-icon" onclick="increaseBasketItem(@item.ProductId)"><i class="ki ki-plus icon-xs"></i></button>
                                </div>
                            </div>
                            <a href="#" class="symbol symbol-70 flex-shrink-0">
                                @if (!string.IsNullOrWhiteSpace(item.PictureAddress))
                                {
                                    <img src="@item.PictureAddress" onerror="this.src = '/metronic/assets/media/products/product.svg'" style="width: 50px; height: 50px;">
                                }
                                else
                                {
                                    <img src="~/metronic/assets/media/products/product.svg" style="width: 50px; height: 50px;">
                                }
                            </a>
                        </div>
                        <div class="separator separator-solid"></div>
                    }
                }
            </div>
            <div class="p-8">
                @if (Model.Any())
                {
                    <div class="d-flex align-items-center justify-content-between mb-7">
                        <span class="font-weight-bold text-muted font-size-sm mr-2">جمع</span>
                        <span class="font-weight-bolder text-primary text-right">@Model.Select(x => x.Price).DefaultIfEmpty(0).Sum().ToString("N0")</span>
                    </div>
                }
                <div class="text-right">
                    @if (!Model.Any())
                    {
                        <a href="@Url.Action("Index","Product")" class="btn btn-success text-weight-bold">
                            مشاهده لیست محصولات
                        </a>
                    }
                    else
                    {
                        <a type="button" class="btn btn-primary text-weight-bold" asp-controller="OrderBasket" asp-action="Index">
                            مشاهده و ثبت سفارش
                        </a>
                        <button type="button" class="btn btn-warning text-weight-bold" onclick="clearBasket()">
                            حذف همه
                        </button>
                    }

                </div>
            </div>
        </form>
    </div>
</div>

src/Pars/Views/Shared/_SidebarMenu.cshtml
<div id="OnlineUsers" dir="rtl">
    <cache expires-after="@TimeSpan.FromMinutes(1)">
        <vc:online-users numbers-to-take="5" minutes-to-take="5" show-more-items-link="true"></vc:online-users>
    </cache>
</div>

<div id="TodayBirthDays" dir="rtl">
    <cache expires-after="@TimeSpan.FromMinutes(5)">
        <vc:today-birth-days></vc:today-birth-days>
    </cache>
</div>

src/Pars/Views/Shared/_UserMenu.cshtml
@inject IUsersPhotoService PhotoService

@{
    var displayName = User.Identity.GetUserDisplayName();
    var photoUrl = PhotoService.GetCurrentUserPhotoUrl();
}

<div class="navbar-nav">
    <div class="dropdown">
        <a  class="nav-item nav-link dropdown-toggle" data-toggle="dropdown"
           id="userDropdown" aria-haspopup="true"
           aria-expanded="false" href="#">
            <img class="img-thumbnail userImage" src="@photoUrl" alt="@displayName" asp-append-version="true"
                 onerror="this.style.visibility = 'hidden';this.width=0; this.height=0;" />
            <span class="author">@displayName</span>
        </a>
        <div class="dropdown-menu" aria-labelledby="userDropdown">
                <a class="dropdown-item" asp-controller="UserCard" asp-action="Index" asp-area="@AreaConstants.IdentityArea">
                    <span class="mr-1 fas fa-user" aria-hidden="true"></span>
                    برگه‌ی کاربری من
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" asp-controller="UserProfile" asp-action="Index" asp-area="@AreaConstants.IdentityArea">
                    <span class="mr-1 fas fa-cog" aria-hidden="true"></span>
                    تنظیمات کاربری من
                </a>
                <a class="dropdown-item" asp-controller="ChangePassword" asp-action="Index" asp-area="@AreaConstants.IdentityArea">
                    <span class="mr-1 fas fa-asterisk" aria-hidden="true"></span>
                    تغییر کلمه‌ی عبور
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" asp-controller="Login" asp-action="LogOff" asp-area="@AreaConstants.IdentityArea">
                    <span class="mr-1 fas fa-sign-out-alt" aria-hidden="true"></span>
                    خروج
                </a>
        </div>
    </div>
</div>